### ISSUE TITLE
resign not working correctly

### ISSUE THREAD

**Issue by HikariSpigot** [WeLoveOpenSourcePlugins/item-signature#6]
If you disable the resign option in config, the plugin says that you can't resign this Item even if it isnt even signed

**Comment by Paul2708** [comment]
Hey, this issue refers to https://github.com/WeLoveOpenSourcePlugins/item-signature/pull/5 and is already fixed. I will release a new version as soon as possible!

**Comment by Paul2708** [comment]
The latest release contains the bug fix. If the issue still occurs, just reopen the issue. Thanks :)
